package com.echo.identity_l0

import com.echo.shared_data.cluster.ClusterIds
import org.tessellation.currency.l0.CurrencyL0App

/**
 * Echo Identity Metagraph L0 — consensus layer for the Identity Metagraph.
 *
 * Phase 1 responsibilities:
 *   - Coordinate snapshots that fold L1 identity updates (VC issuance,
 *     trust tier commitments, StatusList2021 batches, EchoOrgRoleCredentials)
 *     into immutable on-chain state (`IdentityOnChainState`).
 *   - Single project-operated validator node in Phase 1; community
 *     validators added Phase 4+.
 *
 * The Identity Metagraph is intentionally separate from Currency L0 and
 * Data L1 so identity throughput, validator economics, and snapshot cadence
 * can be tuned independently. See `IdentityTypes.scala` for the on-chain
 * state schema.
 *
 * NOTE on cluster IDs: The default UUID is a deterministic non-zero value
 * tied to the local Phase-1 testnet. Production / shared environments must
 * override `IDENTITY_L0_CLUSTER_ID` to a per-environment UUID generated by
 * `uuidgen` before deploy.
 */
object Main extends CurrencyL0App(
  name      = "echo-identity-l0",
  header    = "Echo Identity Metagraph L0",
  clusterId = ClusterIds.identityL0,
  version   = "0.1.0"
) {

  /** Allowed VC types the Identity Metagraph accepts in Phase 1. */
  val SupportedCredentialTypes: Set[String] = Set(
    "TrustTierCredential",
    "EchoOrgRoleCredential",
    "KYCCredential",
    "ProfessionalCredential"
  )
}

